stages:
    - build

variables:
    GIT_SUBMODULE_STRATEGY: normal

build-debian:
    image: registry.videolan.org/vlc-debian-unstable:20210315112333
    stage: build
    except:
        - schedules
    tags:
        - docker
        - amd64
    script:
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-macos:
    stage: build
    except:
        - schedules
    tags:
        - monterey
        - amd64
    script:
        - CONTRIB_TARBALL=`curl -s https://artifacts.videolan.org/vlc/macos-x86_64/SHA512SUM 2>/dev/null | cut -d '/' -f 2`
        - curl -sS -O https://artifacts.videolan.org/vlc/macos-x86_64/$CONTRIB_TARBALL
        - tar xf "$CONTRIB_TARBALL"
        - cd x86_64-apple-darwin19
        - curl -sS -o ./change_prefix.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/contrib/src/change_prefix.sh'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`pwd -P`/lib/pkgconfig/"
        - cd ../
        - export PATH="/Users/videolanci/sandbox/bin:$PATH"
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win64:
    image: registry.videolan.org/vlc-debian-win64:20201106143728
    stage: build
    except:
        - schedules
    tags:
        - docker
        - amd64
    script:
        - CONTRIB_TARBALL=`wget --output-document - https://artifacts.videolan.org/vlc/win64/SHA512SUM 2>/dev/null | cut -d '/' -f 2`
        - wget -nv https://artifacts.videolan.org/vlc/win64/$CONTRIB_TARBALL
        - tar xf "$CONTRIB_TARBALL"
        - cd x86_64-w64-mingw32
        - wget -nv -O ./change_prefix.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/contrib/src/change_prefix.sh'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - cd ..
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`realpath x86_64-w64-mingw32`/lib/pkgconfig/"
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure --host=x86_64-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win32:
    image: registry.videolan.org/vlc-debian-win32:20201106141924
    stage: build
    except:
        - schedules
    tags:
        - docker
        - amd64
    script:
        - CONTRIB_TARBALL=`wget --output-document - https://artifacts.videolan.org/vlc/win32/SHA512SUM 2>/dev/null | cut -d '/' -f 2`
        - wget -nv https://artifacts.videolan.org/vlc/win32/$CONTRIB_TARBALL
        - tar xf "$CONTRIB_TARBALL"
        - cd i686-w64-mingw32
        - wget -nv -O ./change_prefix.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/contrib/src/change_prefix.sh'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - cd ..
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`realpath i686-w64-mingw32`/lib/pkgconfig/"
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure --host=i686-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

pages:
    stage: build
    image:
        name: registry.videolan.org/vlc-debian-unstable:20210315112333
    tags:
        - docker
        - amd64
    script:
        - doxygen doc/doxygen-config
        - mv doc/doxygen/html public
    artifacts:
        paths:
            - public
    only:
        - schedules
