stages:
    - build

variables:
    GIT_SUBMODULE_STRATEGY: normal

build-debian:
    image: registry.videolan.org:5000/vlc-debian-unstable:20181128113529
    stage: build
    tags:
        - debian
        - amd64
    script:
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-macos:
    stage: build
    tags:
        - macos
    script:
        - curl -sS -O https://nightlies.videolan.org/build/contribs/vlc-contrib-x86_64-apple-darwin18-latest.tar.bz2
        - tar xf vlc-contrib-x86_64-apple-darwin18-latest.tar.bz2
        - cd x86_64-apple-darwin18
        - curl -sS -o ./change_prefix.sh 'https://git.videolan.org/?p=vlc.git;a=blob_plain;f=contrib/src/change_prefix.sh;hb=HEAD'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`pwd -P`/lib/pkgconfig/"
        - cd ../
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win64:
    image: registry.videolan.org:5000/vlc-debian-win64:20181107154313
    stage: build
    tags:
        - debian
        - amd64
        - win64
    script:
        - wget -nv https://nightlies.videolan.org/build/contribs/vlc-contrib-x86_64-w64-mingw32-latest.tar.bz2
        - tar xf vlc-contrib-x86_64-w64-mingw32-latest.tar.bz2
        - cd x86_64-w64-mingw32
        - wget -nv -O ./change_prefix.sh 'https://git.videolan.org/?p=vlc.git;a=blob_plain;f=contrib/src/change_prefix.sh;hb=HEAD'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - cd ..
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`realpath x86_64-w64-mingw32`/lib/pkgconfig/"
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure --host=x86_64-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win32:
    image: registry.videolan.org:5000/vlc-debian-win32:20181107151708
    stage: build
    tags:
        - debian
        - amd64
        - win32
    script:
        - wget -nv https://nightlies.videolan.org/build/contribs/vlc-contrib-i686-w64-mingw32-latest.tar.bz2
        - tar xf vlc-contrib-i686-w64-mingw32-latest.tar.bz2
        - cd i686-w64-mingw32
        - wget -nv -O ./change_prefix.sh 'https://git.videolan.org/?p=vlc.git;a=blob_plain;f=contrib/src/change_prefix.sh;hb=HEAD'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - cd ..
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`realpath i686-w64-mingw32`/lib/pkgconfig/"
        - mkdir build
        - cd build
        - ../bootstrap
        - ../configure --host=i686-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)
