/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_videolan_Libbluray */

#ifndef _Included_org_videolan_Libbluray
#define _Included_org_videolan_Libbluray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_videolan_Libbluray
 * Method:    getCurrentTitleNumN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_getCurrentTitleNumN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    writeGPRN
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_writeGPRN
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    readGPRN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_readGPRN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    readPSRN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_readPSRN
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
