/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_videolan_Libbluray */

#ifndef WIN32
#undef JNIEXPORT
#define JNIEXPORT static
#endif

#ifndef _Included_org_videolan_Libbluray
#define _Included_org_videolan_Libbluray
#ifdef __cplusplus
extern "C" {
#endif
#undef org_videolan_Libbluray_BDJ_EVENT_CHAPTER
#define org_videolan_Libbluray_BDJ_EVENT_CHAPTER 1L
#undef org_videolan_Libbluray_BDJ_EVENT_PLAYITEM
#define org_videolan_Libbluray_BDJ_EVENT_PLAYITEM 2L
#undef org_videolan_Libbluray_BDJ_EVENT_ANGLE
#define org_videolan_Libbluray_BDJ_EVENT_ANGLE 3L
#undef org_videolan_Libbluray_BDJ_EVENT_SUBTITLE
#define org_videolan_Libbluray_BDJ_EVENT_SUBTITLE 4L
#undef org_videolan_Libbluray_BDJ_EVENT_PIP
#define org_videolan_Libbluray_BDJ_EVENT_PIP 5L
#undef org_videolan_Libbluray_BDJ_EVENT_END_OF_PLAYLIST
#define org_videolan_Libbluray_BDJ_EVENT_END_OF_PLAYLIST 6L
#undef org_videolan_Libbluray_BDJ_EVENT_PTS
#define org_videolan_Libbluray_BDJ_EVENT_PTS 7L
#undef org_videolan_Libbluray_BDJ_EVENT_VK_KEY
#define org_videolan_Libbluray_BDJ_EVENT_VK_KEY 8L
#undef org_videolan_Libbluray_PSR_IG_STREAM_ID
#define org_videolan_Libbluray_PSR_IG_STREAM_ID 0L
#undef org_videolan_Libbluray_PSR_PRIMARY_AUDIO_ID
#define org_videolan_Libbluray_PSR_PRIMARY_AUDIO_ID 1L
#undef org_videolan_Libbluray_PSR_PG_STREAM
#define org_videolan_Libbluray_PSR_PG_STREAM 2L
#undef org_videolan_Libbluray_PSR_ANGLE_NUMBER
#define org_videolan_Libbluray_PSR_ANGLE_NUMBER 3L
#undef org_videolan_Libbluray_PSR_TITLE_NUMBER
#define org_videolan_Libbluray_PSR_TITLE_NUMBER 4L
#undef org_videolan_Libbluray_PSR_CHAPTER
#define org_videolan_Libbluray_PSR_CHAPTER 5L
#undef org_videolan_Libbluray_PSR_PLAYLIST
#define org_videolan_Libbluray_PSR_PLAYLIST 6L
#undef org_videolan_Libbluray_PSR_PLAYITEM
#define org_videolan_Libbluray_PSR_PLAYITEM 7L
#undef org_videolan_Libbluray_PSR_TIME
#define org_videolan_Libbluray_PSR_TIME 8L
#undef org_videolan_Libbluray_PSR_NAV_TIMER
#define org_videolan_Libbluray_PSR_NAV_TIMER 9L
#undef org_videolan_Libbluray_PSR_SELECTED_BUTTON_ID
#define org_videolan_Libbluray_PSR_SELECTED_BUTTON_ID 10L
#undef org_videolan_Libbluray_PSR_MENU_PAGE_ID
#define org_videolan_Libbluray_PSR_MENU_PAGE_ID 11L
#undef org_videolan_Libbluray_PSR_STYLE
#define org_videolan_Libbluray_PSR_STYLE 12L
#undef org_videolan_Libbluray_PSR_PARENTAL
#define org_videolan_Libbluray_PSR_PARENTAL 13L
#undef org_videolan_Libbluray_PSR_SECONDARY_AUDIO_VIDEO
#define org_videolan_Libbluray_PSR_SECONDARY_AUDIO_VIDEO 14L
#undef org_videolan_Libbluray_PSR_AUDIO_CAP
#define org_videolan_Libbluray_PSR_AUDIO_CAP 15L
#undef org_videolan_Libbluray_PSR_AUDIO_LANG
#define org_videolan_Libbluray_PSR_AUDIO_LANG 16L
#undef org_videolan_Libbluray_PSR_PG_AND_SUB_LANG
#define org_videolan_Libbluray_PSR_PG_AND_SUB_LANG 17L
#undef org_videolan_Libbluray_PSR_MENU_LANG
#define org_videolan_Libbluray_PSR_MENU_LANG 18L
#undef org_videolan_Libbluray_PSR_COUNTRY
#define org_videolan_Libbluray_PSR_COUNTRY 19L
#undef org_videolan_Libbluray_PSR_REGION
#define org_videolan_Libbluray_PSR_REGION 20L
#undef org_videolan_Libbluray_PSR_VIDEO_CAP
#define org_videolan_Libbluray_PSR_VIDEO_CAP 29L
#undef org_videolan_Libbluray_PSR_TEXT_CAP
#define org_videolan_Libbluray_PSR_TEXT_CAP 30L
#undef org_videolan_Libbluray_PSR_PROFILE_VERSION
#define org_videolan_Libbluray_PSR_PROFILE_VERSION 31L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR4
#define org_videolan_Libbluray_PSR_BACKUP_PSR4 36L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR5
#define org_videolan_Libbluray_PSR_BACKUP_PSR5 37L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR6
#define org_videolan_Libbluray_PSR_BACKUP_PSR6 38L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR7
#define org_videolan_Libbluray_PSR_BACKUP_PSR7 39L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR8
#define org_videolan_Libbluray_PSR_BACKUP_PSR8 40L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR10
#define org_videolan_Libbluray_PSR_BACKUP_PSR10 42L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR11
#define org_videolan_Libbluray_PSR_BACKUP_PSR11 43L
#undef org_videolan_Libbluray_PSR_BACKUP_PSR12
#define org_videolan_Libbluray_PSR_BACKUP_PSR12 44L
/*
 * Class:     org_videolan_Libbluray
 * Method:    getVolumeIDN
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_videolan_Libbluray_getVolumeIDN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getPMSNN
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_videolan_Libbluray_getPMSNN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getDeviceBindingIDN
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_videolan_Libbluray_getDeviceBindingIDN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getUOMask
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_getUOMaskN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getUOMask
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_org_videolan_Libbluray_setUOMaskN
(JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getTitleInfoN
 * Signature: (JI)Lorg/videolan/TitleInfo;
 */
JNIEXPORT jobject JNICALL Java_org_videolan_Libbluray_getTitleInfoN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getPlaylistInfoN
 * Signature: (JI)Lorg/videolan/PlaylistInfo;
 */
JNIEXPORT jobject JNICALL Java_org_videolan_Libbluray_getPlaylistInfoN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getTitlesN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_getTitlesN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    seekN
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_seekN
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    seekTimeN
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_seekTimeN
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    seekChapterN
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_seekChapterN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    chapterPosN
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_chapterPosN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getCurrentChapterN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_getCurrentChapterN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    seekMarkN
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_seekMarkN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    seekPlayItemN
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_seekPlayItemN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    selectPlaylistN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_selectPlaylistN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    selectTitleN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_selectTitleN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    selectAngleN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_selectAngleN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    seamlessAngleChangeN
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_videolan_Libbluray_seamlessAngleChangeN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getTitleSizeN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_getTitleSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getCurrentTitleN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_getCurrentTitleN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getCurrentAngleN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_getCurrentAngleN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    tellN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_tellN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    tellTimeN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_Libbluray_tellTimeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_videolan_Libbluray
 * Method:    selectRateN
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_selectRateN
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_videolan_Libbluray
 * Method:    writeGPRN
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_writeGPRN
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    writePSRN
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_writePSRN
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    readGPRN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_readGPRN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    readPSRN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_Libbluray_readPSRN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_videolan_Libbluray
 * Method:    getBdjoN
 * Signature: (JLjava/lang/String;)Lorg/videolan/bdjo/Bdjo;
 */
JNIEXPORT jobject JNICALL Java_org_videolan_Libbluray_getBdjoN
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_videolan_Libbluray
 * Method:    updateGraphicN
 * Signature: (JII[IIIII)V
 */
JNIEXPORT void JNICALL Java_org_videolan_Libbluray_updateGraphicN
(JNIEnv *, jclass, jlong, jint, jint, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
